apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: microservice-a/
    repoURL: https://github.com/d-kuro/argocd-demo
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
